#!/usr/bin/env node
/**
 * Generate TypeScript types from committed brewery OpenAPI JSON (Phase E).
 * Source of truth: services/api/openapi/brewery.json
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(__dirname, "..");
const repoRoot = join(pkgRoot, "../../../..");
const outDir = join(pkgRoot, "src/generated");
const inputPath = join(repoRoot, "services/api/openapi/brewery.json");
const outputPath = join(outDir, "brewery.openapi.ts");

const BANNER =
  "/** Generated by `npm run openapi:codegen` in @umbraculum/brewery-api-client — do not edit. */\n";

async function renderSpec() {
  const source = readFileSync(inputPath, "utf8");
  const ast = await openapiTS(source, {
    exportType: true,
  });
  return astToString(ast);
}

async function generate() {
  mkdirSync(outDir, { recursive: true });
  const body = await renderSpec();
  writeFileSync(outputPath, `${BANNER}${body}`);
  console.log(`openapi-codegen: wrote ${outputPath}`);
}

async function check() {
  const expected = readFileSync(outputPath, "utf8");
  const fresh = `${BANNER}${await renderSpec()}`;
  if (fresh !== expected) {
    console.error(
      "openapi-codegen: drift — run npm run openapi:codegen -w @umbraculum/brewery-api-client",
    );
    process.exit(1);
  }
  console.log("openapi-codegen: check OK");
}

const mode = process.argv.includes("--check") ? "check" : "generate";

if (mode === "check") {
  await check();
} else {
  await generate();
}
