#!/usr/bin/env node
/**
 * Generate TypeScript types from committed OpenAPI JSON artifacts (Phase E).
 * Source of truth: services/api/openapi/{openapi,brewery}.json
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(__dirname, "..");
const repoRoot = join(pkgRoot, "../..");
const outDir = join(pkgRoot, "src/generated");

const BANNER =
  "/** Generated by `npm run openapi:codegen` in @umbraculum/api-client — do not edit. */\n";

/** @type {ReadonlyArray<{ id: string; input: string; output: string }>} */
const SPECS = [
  {
    id: "platform",
    input: join(repoRoot, "services/api/openapi/openapi.json"),
    output: join(outDir, "platform.openapi.ts"),
  },
  {
    id: "brewery",
    input: join(repoRoot, "services/api/openapi/brewery.json"),
    output: join(outDir, "brewery.openapi.ts"),
  },
];

async function renderSpec(inputPath) {
  const source = readFileSync(inputPath, "utf8");
  const ast = await openapiTS(source, {
    exportType: true,
  });
  return astToString(ast);
}

async function generateAll() {
  mkdirSync(outDir, { recursive: true });
  for (const spec of SPECS) {
    const body = await renderSpec(spec.input);
    writeFileSync(spec.output, `${BANNER}${body}`);
    console.log(`openapi-codegen: wrote ${spec.output}`);
  }
}

async function checkAll() {
  for (const spec of SPECS) {
    const expected = readFileSync(spec.output, "utf8");
    const fresh = `${BANNER}${await renderSpec(spec.input)}`;
    if (fresh !== expected) {
      console.error(
        `openapi-codegen: drift in ${spec.id} — run npm run openapi:codegen -w @umbraculum/api-client`,
      );
      process.exit(1);
    }
  }
  console.log("openapi-codegen: check OK");
}

const mode = process.argv.includes("--check") ? "check" : "generate";

if (mode === "check") {
  await checkAll();
} else {
  await generateAll();
}
