/**
 * Root ESLint flat config (ESLint v9+).
 *
 * Scope: Medium (per `docs/LINTING.md`). See that doc for the value/cost
 * matrix, the HIGH-scope upgrade plan, and the rationale for every rule
 * here.
 *
 * Headline guardrails:
 *
 *  - `react-hooks/rules-of-hooks`: error. Catches the hook-rules violations
 *    TS will never see.
 *  - `react-hooks/exhaustive-deps`: warn (HIGH-scope upgrades to error).
 *  - `jsx-a11y/recommended`: catches a11y regressions at the source, ahead
 *    of the axe-core checks in the Playwright smoke suite.
 *  - `no-restricted-imports` scoped to `packages/ui/src/{ai,charts}/**`:
 *    forbids raw tamagui `Button`/`Input`/`Checkbox` imports in cross-
 *    platform components (they leak React Native a11y props to the DOM on
 *    web). Components must use the platform-forking wrappers in
 *    `packages/ui/src/primitives/*`.
 *
 * Environment globals are declared per-file-glob using the `globals`
 * package — flat config does not auto-detect environments.
 */
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import jsxA11y from "eslint-plugin-jsx-a11y";
import boundaries from "eslint-plugin-boundaries";
import globals from "globals";

export default [
  // -------------------------------------------------------------------
  // Ignored paths — never lint these.
  // -------------------------------------------------------------------
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/build/**",
      // Generated by Docusaurus — never hand-edited; absent on CI checkout
      "**/.docusaurus/**",
      "**/coverage/**",
      "**/.expo/**",
      "**/.expo-shared/**",
      "**/web-build/**",
      "**/ios/**",
      "**/android/**",
      "**/playwright-report/**",
      "**/test-results/**",
      "**/expo-env.d.ts",
      // Generated by Next.js on `next dev` — never hand-edited
      "**/next-env.d.ts",
      // Generated by Tamagui's compiler — never hand-edited, very large
      "**/.tamagui/**",
      // Generated by Prisma — never hand-edited
      "services/api/prisma/migrations/**",
      // Generated by tsup, regenerated by ./scripts/build-packages-in-docker.sh
      "packages/*/dist/**",
      // Generated by @umbraculum/api-client openapi:codegen
      "packages/api-client/src/generated/**",
      // Vendored / third-party text
      "LICENSE",
      // RFC-0003 validation-library spike (Zod v4 vs Valibot) — exploratory
      // Phase 1 code per spike/validation-library/README.md. Excluded from
      // lint because spike code intentionally includes async-no-await
      // Fastify route handlers + unused-type imports as part of the
      // side-by-side comparison artifact; holding it to production-grade
      // lint rules destroys the comparison value. Migration PRs (Phase 2+)
      // will re-introduce the patterns under standard lint coverage.
      "spike/**",
    ],
  },

  // -------------------------------------------------------------------
  // Base JS + TS recommended.
  // -------------------------------------------------------------------
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // -------------------------------------------------------------------
  // Project-wide language options: ES2022 + browser + Node globals.
  // (Broad on purpose for the Medium scope. HIGH-scope narrows this
  // per-package — e.g. `services/api/**` only needs Node globals.)
  // -------------------------------------------------------------------
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2022,
        // React Native + Tamagui runtime hints used at runtime
        __DEV__: "readonly",
      },
    },
  },

  // -------------------------------------------------------------------
  // Type-aware parser for TS files (HIGH-full Phase 2 onward).
  //
  // Enables the 7 promise-related rules below to read TypeScript types.
  // Scoped to `.ts/.tsx` only so non-TS files (.cjs, .mjs, .js configs)
  // stay on the cheap parser. Adds ~30s to a full-repo lint; the savings
  // it unlocks (real promise-correctness bug catches) are worth the cost.
  //
  // `allowDefaultProject` is the escape hatch for TS files outside any
  // tsconfig include (vitest configs, ad-hoc scripts).
  //
  // typescript-eslint enforces a hard ceiling of 8 matching files via
  // `maximumDefaultProjectFileMatchCount`; crossing it produces:
  //   "Parsing error: Too many files (>8) have matched the default project."
  // Bumping that ceiling is documented as a perf footgun (the parameter
  // name literally ends in `_THIS_WILL_SLOW_DOWN_LINTING`). Instead, the
  // preferred way to keep an orphan TS file out of this list is to add
  // it to the owning package's `tsconfig.json` `include` array — that
  // binds it to a real project and removes it from default-project
  // matching entirely.
  //
  // The five entries below are the files for which that fix is NOT
  // available without invasive structural change:
  //
  //  - `services/api/vitest.config.ts`, `packages/beerjson/vitest.config.ts`:
  //    the package `tsconfig.json` is the build config (sets
  //    `rootDir: "src"`, no `noEmit`), so adding a root-level file to
  //    `include` would trip TS6059 ("rootDir is expected to contain all
  //    source files") in the typecheck CI job.
  //  - `packages/core/vitest.config.ts`, `packages/core/src/index.d.ts`:
  //    `packages/core/` has no `tsconfig.json` at all (structural gap;
  //    out of scope for this lint hotfix — track via follow-up).
  //  - `scripts/check-web-url-segments.ts`: there is no `scripts/`
  //    tsconfig at all (same structural gap as `packages/core/`).
  //
  // When adding a new TS config file (vitest, tsup, ad-hoc script):
  //   1. Add it to the owning workspace's `tsconfig.json` `include`
  //      first (the cheap, scalable fix).
  //   2. Only add it here if (1) would conflict with `rootDir` or no
  //      sibling tsconfig exists — and document the reason inline so
  //      future contributors don't re-bloat this list.
  // -------------------------------------------------------------------
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            "services/api/vitest.config.ts",
            "packages/beerjson/vitest.config.ts",
            "packages/core/vitest.config.ts",
            "packages/core/src/index.d.ts",
            "scripts/check-web-url-segments.ts",
            "scripts/audit/solid-inventory.ts",
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // -------------------------------------------------------------------
  // Project-wide rule tweaks. MUST come before any file-glob override
  // blocks below — flat-config later blocks override earlier ones, so
  // anything we want a per-glob override (e.g. "@typescript-eslint/
  // no-explicit-any: off" for tests) to actually take effect must
  // appear AFTER this block, not before.
  // -------------------------------------------------------------------
  {
    rules: {
      // TS already enforces this and the TS error message is clearer.
      "no-unused-vars": "off",
      // Allow underscore-prefixed unused (e.g. _unusedProps).
      // Promoted from warn → error in HIGH-staged Phase 6c (2026-05-16).
      // Repo was swept warning-free across apps/native, apps/web,
      // services/api, and packages/** before this promotion landed.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // Promoted from warn → error in HIGH-staged Phase 6c (2026-05-16).
      // The repo is now `any`-free (the staged HIGH cleanup landed in
      // Phases 1–6b). When a genuine "this is dynamic" escape hatch is
      // needed, prefer typing as `unknown` and narrowing; if `any` is
      // truly unavoidable, disable per-line with a `// eslint-disable-
      // next-line @typescript-eslint/no-explicit-any -- <reason>`.
      "@typescript-eslint/no-explicit-any": "error",
      // Allow `interface X extends Y {}` (Tamagui's module augmentation
      // pattern, `interface TamaguiCustomConfig extends AppConfig {}`, and
      // similar "named type alias via interface" patterns). Still flag
      // truly empty `interface X {}` and `type X = {}` because those
      // accept any non-null value.
      //
      // Promoted from `warn` to `error` 2026-05-16 (HIGH-full housekeeping
      // commit, post-Phase-5e). The repo has had zero violations of this
      // rule since the HIGH-light landing — the warn level was a
      // safety-net during the staged cleanup. Now that all type-aware
      // rules are at `error`, having one lone warning-level rule was the
      // last drift surface; promoting it removes the ambiguity (every
      // rule now fails CI uniformly).
      "@typescript-eslint/no-empty-object-type": [
        "error",
        { allowInterfaces: "with-single-extends" },
      ],
    },
  },

  // -------------------------------------------------------------------
  // HIGH-full Phase 2 — Tier A: Promise correctness (TS-only).
  //
  // All seven type-aware rules at `error` (promoted from `warn` by
  // Phase 5 after Phase 2 reached zero warnings repo-wide).
  //
  // Scoped to `.ts/.tsx` because the rules require the type-aware
  // parser block above (which is also `.ts/.tsx`-scoped).
  //
  //  - no-floating-promises: orphan Promises that swallow rejections.
  //  - no-misused-promises: async fn passed where void return expected
  //    (event handlers, setTimeout callbacks, etc.).
  //  - await-thenable: `await` on a non-Promise (no-op signaling bug).
  //  - require-await: async fn with no `await` (return type mismatch).
  //  - prefer-promise-reject-errors / only-throw-error: reject/throw
  //    must be Error instances, not strings.
  //  - no-implied-eval: setTimeout("string"), new Function(string).
  // -------------------------------------------------------------------
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/prefer-promise-reject-errors": "error",
      "@typescript-eslint/no-implied-eval": "error",
      "@typescript-eslint/only-throw-error": "error",
    },
  },

  // -------------------------------------------------------------------
  // HIGH-full Phase 3 — Tier C-narrow: services/api `no-unsafe-*`.
  //
  // All five type-aware unsafe-* rules at `error` (promoted from `warn`
  // by Phase 5 after Phase 3 reached zero warnings on `services/api/**`,
  // covering both `src/**` and `prisma/seed.ts`).
  //
  // Tests are deliberately exempted via the test-files relaxation
  // block below (later block wins in flat config). Test code uses
  // the `JSON.parse(res.body) as Shape` pattern by convention; type-
  // narrowing every test response is high-volume mechanical work
  // with low bug-catching value, and matches the existing test-file
  // relaxation of `no-explicit-any`.
  //
  // The contracts/validation strategy
  // (docs/CONTRACTS-VALIDATION-STRATEGY.md) explicitly says we stay
  // on hand-rolled validators, so the fix pattern here is:
  //   1. Type the boundary as `unknown` (or a narrow input type).
  //   2. Narrow with type guards or hand-rolled `parseX()` helpers.
  //   3. Do NOT introduce Zod/Valibot — that's a separate decision
  //      with its own trigger criteria.
  // -------------------------------------------------------------------
  {
    files: ["services/api/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-unsafe-return": "error",
    },
  },

  // -------------------------------------------------------------------
  // HIGH-full Phase 4 + 5g — Tier C-wide: apps/web + apps/native
  // `no-unsafe-*`.
  //
  // Same five type-aware rules as Phase 3, scoped to apps/web and
  // apps/native, at `error`.
  //
  // Phase 4 (apps/web, promoted to error by Phase 5c, 2026-05-16):
  // The original plan called this "the Tamagui wall" with an estimated
  // 266 warnings split across 4a/4b/4c sub-strategies (per-site
  // disable / Tamagui adapter improvements / hybrid). Reality
  // (post-Phase-3 remeasurement): 304 raw warnings, 290 of which
  // traced to a single root cause — four water-related pages reading
  // `profiles?.account` after the `account → workspace` rename in
  // commit `87876d0` missed those consumers. Tamagui prop typing was
  // responsible for ~6 warnings, not 266. Phase 4 became a stale-
  // rename cleanup (4b) plus a small tail (4c), not a Tamagui
  // adapter project.
  //
  // Phase 5g (apps/native, landed 2026-05-16): originally excluded
  // from Phase 4 because the HIGH-full measurement reported only 3
  // warnings in apps/native (smallest first-party workspace by an
  // order of magnitude) and the IDE-cost objection at the time was
  // a real concern. With the editor-config split landed in Phase 5a
  // (which strips type-aware rules from editor lint regardless of
  // file scope), the IDE-cost objection is gone. The 3 known
  // warnings turned out to all be in `apps/native/src/navigation/
  // AppNavigator.tsx` — a single inline `RootStack.Screen` render-
  // prop where `({ navigation })` was untyped. Fixed by importing
  // `NativeStackScreenProps<RootStackParamList, "SelectWorkspace">`
  // and annotating the destructured argument; pattern matches
  // `useNavigation<NavigationProp<RootStackParamList>>()` already
  // used elsewhere in the workspace. Promoted directly to `error`
  // in the same commit (no warn-staging needed for a 3-warning,
  // single-file surface).
  //
  // Tests are exempted via the test-files relaxation block below
  // (later block wins), matching Phase 3a. Playwright e2e specs in
  // `apps/web/e2e/**` are covered by the `**/e2e/**` glob in that
  // block.
  // -------------------------------------------------------------------
  {
    files: ["apps/{web,native}/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-unsafe-return": "error",
    },
  },

  // -------------------------------------------------------------------
  // RFC-0003 — packages/*-contracts/ runtime-validation discipline.
  //
  // Per RFC-0003 Decision A (Accepted 2026-05-19), every boundary
  // payload in `packages/contracts/`, `packages/automation-contracts/`,
  // and the 4 future module-contracts packages MUST be validated via a
  // Zod schema. Hand-rolled `parseX(unknown): X` functions are no longer
  // permitted as the primary validator — they may exist only as thin
  // wrappers around `Schema.parse()` for call-site stability.
  //
  // Detection: forbid in contracts source any declared type-guard helper
  // matching the hand-rolled drift pattern (`function isX(v: unknown):
  // v is X`). The lint surfaces drift; the fix is to replace with a Zod
  // schema and drop the helper.
  //
  // Test files are exempted via the later test-files relaxation block
  // (they may still use hand-rolled assertion helpers).
  //
  // See `docs/rfcs/0003-validation-library-adoption.md` Decision E, and
  // `.cursor/plugins/local/umbraculum-node-react-cursor-assistant/rules/
  // 22-typescript-contracts-runtime-validation.mdc` for the IDE guidance.
  // -------------------------------------------------------------------
  {
    files: ["packages/*-contracts/src/**/*.{ts,tsx}", "packages/contracts/src/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "TSTypePredicate[parameterName.name='v'] > TSTypeReference[typeName.name=/^[A-Z]/]",
          message:
            "RFC-0003: hand-rolled type-guard helpers (`function isX(v: unknown): v is X`) are forbidden in packages/*-contracts/. Use a Zod schema (z.object/...) and infer the type via z.infer<typeof Schema>. See docs/rfcs/0003-validation-library-adoption.md.",
        },
      ],
    },
  },

  // -------------------------------------------------------------------
  // React hook rules (manual; the plugin doesn't ship a flat preset).
  // -------------------------------------------------------------------
  {
    files: ["**/*.{ts,tsx,js,jsx,mjs,cjs}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      // Promoted from warn → error in HIGH-light. Catches stale-closure
      // bugs that TS cannot see (e.g. an effect that reads `state` but
      // omits it from its deps array). When a missing dep is intentional,
      // use `// eslint-disable-next-line react-hooks/exhaustive-deps --
      // <reason>`.
      "react-hooks/exhaustive-deps": "error",
    },
  },

  // -------------------------------------------------------------------
  // JSX accessibility (recommended) — only on TSX/JSX.
  // -------------------------------------------------------------------
  {
    files: ["**/*.{tsx,jsx}"],
    plugins: { "jsx-a11y": jsxA11y },
    rules: jsxA11y.configs.recommended.rules,
  },

  // -------------------------------------------------------------------
  // Cross-platform component discipline.
  //
  // Files under `packages/ui/src/{ai,charts}/**` are consumed by BOTH web
  // AND native. Importing `Button` / `Input` / `Checkbox` from raw
  // `tamagui` works on native but leaks React Native accessibility props
  // (`accessibilityLabel`, `accessibilityRole`) to the DOM on web, which
  // React 19 warns about. The project ships platform-forking primitives
  // in `packages/ui/src/primitives/{Button,Input,BrewCheckbox}.tsx` that
  // do the right thing on each platform.
  //
  // This rule forbids the raw imports in the cross-platform folders only;
  // web-only pages (`apps/web/**`) and native-only screens
  // (`apps/native/**`) are unaffected.
  // -------------------------------------------------------------------
  {
    files: ["packages/ui/src/ai/**/*.{ts,tsx}", "packages/ui/src/charts/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "tamagui",
              importNames: ["Button", "Input", "Checkbox"],
              message:
                "Cross-platform components must use platform-forking primitives: import { Button } from '../primitives/Button', { Input } from '../primitives/Input', { BrewCheckbox } from '../primitives/BrewCheckbox'. Raw tamagui Button/Input/Checkbox leak accessibilityLabel to the DOM on web. See docs/LINTING.md.",
            },
          ],
        },
      ],
    },
  },

  // -------------------------------------------------------------------
  // CommonJS files: allow `require()` and CJS globals.
  // (`.cjs` files are intentionally CommonJS; `.js` files in legacy
  // configs like babel.config.js, metro.config.js can use either.)
  // -------------------------------------------------------------------
  {
    files: ["**/*.cjs", "**/babel.config.js", "**/metro.config.js", "**/app.config.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        ...globals.node,
        ...globals.commonjs,
      },
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },

  // -------------------------------------------------------------------
  // SOLID B5 — canonical module import boundaries (error-level, CI-blocking).
  //
  // Scoped to services/api/src/modules/** per solid-boundaries-eslint-spike.md.
  // Blocks sibling imports (e.g. crp → mrp); allows platform/, domain/,
  // plugins/, and same-module paths. Promoted from warn (A4) 2026-06-04.
  // -------------------------------------------------------------------
  {
    files: ["services/api/src/modules/**/*.{ts,tsx}"],
    plugins: { boundaries },
    settings: {
      "import/resolver": {
        typescript: {
          alwaysTryTypes: true,
          project: ["services/api/tsconfig.json"],
        },
      },
      "boundaries/elements": [
        {
          type: "platform",
          pattern: "services/api/src/platform/**",
          mode: "full",
        },
        {
          type: "domain",
          pattern: "services/api/src/domain/**",
          mode: "full",
        },
        {
          type: "plugins",
          pattern: "services/api/src/plugins/**",
          mode: "full",
        },
        {
          type: "canonical-module",
          pattern: "services/api/src/modules/*/**",
          mode: "file",
          capture: ["moduleCode"],
        },
      ],
    },
    rules: {
      "boundaries/no-unknown-files": "off",
      "boundaries/element-types": [
        "error",
        {
          default: "allow",
          message:
            "Canonical module ${file.moduleCode} must not import sibling module ${dependency.moduleCode} — use platform/ or *-contracts (SOLID charter).",
          rules: [
            {
              from: [["canonical-module"]],
              disallow: [
                ["canonical-module", { moduleCode: "!${from.moduleCode}" }],
              ],
            },
          ],
        },
      ],
    },
  },

  // -------------------------------------------------------------------
  // SOLID WS5 — app import boundaries (error-level, CI-blocking).
  //
  // Mirrors the API spike structure with an app-scoped pilot:
  //  - forbid apps/* source imports from services/api/**
  //  - forbid sibling segment imports for selected app segment families
  //
  // web-water-shared includes water/_lib/** and water/_hooks/** (cross-segment
  // helpers intentionally shared across mash/sparge/boil segments).
  // web-recipe-edit-shared mirrors that for edit/_lib + edit/_hooks.
  // -------------------------------------------------------------------
  {
    files: ["apps/{web,native}/**/*.{ts,tsx}"],
    plugins: { boundaries },
    settings: {
      "import/resolver": {
        typescript: {
          alwaysTryTypes: true,
          project: ["apps/web/tsconfig.json", "apps/native/tsconfig.json"],
        },
      },
      "boundaries/elements": [
        {
          type: "api-service",
          pattern: "services/api/**",
          mode: "full",
        },
        {
          type: "web-app-shared",
          pattern: "apps/web/{src,app/_components,app/_lib}/**",
          mode: "full",
        },
        {
          type: "web-water-shared",
          pattern: "apps/web/app/recipes/[[]id[]]/water/{_lib,_hooks}/**",
          mode: "full",
        },
        {
          type: "web-water-segment",
          pattern: "apps/web/app/recipes/[[]id[]]/water/*/**",
          mode: "file",
          capture: ["segmentCode"],
        },
        {
          type: "web-recipe-edit-shared",
          pattern: "apps/web/app/recipes/[[]id[]]/edit/{_lib,_hooks}/**",
          mode: "full",
        },
        {
          type: "web-recipe-edit-surface",
          pattern: "apps/web/app/recipes/[[]id[]]/edit/**",
          mode: "full",
        },
        {
          type: "native-app-shared",
          pattern:
            "apps/native/src/{auth,components,i18n,lib,media,navigation,screens,theme,types}/**",
          mode: "full",
        },
        {
          type: "native-module-segment",
          pattern: "apps/native/src/modules/*/**",
          mode: "file",
          capture: ["moduleCode"],
        },
      ],
    },
    rules: {
      "boundaries/no-unknown-files": "off",
      "boundaries/element-types": [
        "error",
        {
          default: "allow",
          message:
            "SOLID WS5: disallowed cross-layer import (${file.type} -> ${dependency.type}) in app boundaries prototype.",
          rules: [
            {
              from: [
                ["web-app-shared"],
                ["web-water-segment"],
                ["web-recipe-edit-surface"],
                ["native-app-shared"],
                ["native-module-segment"],
              ],
              disallow: [["api-service"]],
            },
            {
              from: [["web-water-segment"]],
              allow: [["web-water-shared"], ["web-app-shared"]],
            },
            {
              from: [["web-recipe-edit-surface"]],
              allow: [
                ["web-recipe-edit-shared"],
                ["web-water-shared"],
                ["web-app-shared"],
              ],
            },
            {
              from: [["web-water-segment"]],
              disallow: [
                ["web-water-segment", { segmentCode: "!${from.segmentCode}" }],
              ],
            },
            {
              from: [["native-module-segment"]],
              disallow: [
                ["native-module-segment", { moduleCode: "!${from.moduleCode}" }],
              ],
            },
          ],
        },
      ],
    },
  },

  // -------------------------------------------------------------------
  // Test files: relax a few rules.
  //
  // `no-explicit-any` and `no-unused-expressions` were relaxed during
  // HIGH-staged. The 5 `no-unsafe-*` rules are added here as part of
  // HIGH-full Phase 3: test code uses the `JSON.parse(res.body) as
  // Shape` pattern by convention, and re-typing every Fastify-inject
  // test response yields ~600 mechanical fixes with low bug-catching
  // value (the type assertions are usually correct because the test
  // controls both ends). Source code in `services/api/**` keeps the
  // strong guardrail; tests get the same relaxation pattern as
  // `no-explicit-any`.
  // -------------------------------------------------------------------
  {
    files: [
      "**/*.{test,spec}.{ts,tsx,js,jsx}",
      "**/tests/**",
      "**/e2e/**",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-expressions": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },

  // -------------------------------------------------------------------
  // Playwright e2e fixtures: Playwright's `use` fixture parameter has the
  // same name as React 19's `use()` hook. ESLint's `react-hooks` plugin
  // can't tell them apart, so it false-positives on every Playwright
  // fixture function. Disable the hook rules in e2e directories — these
  // files are not React.
  // -------------------------------------------------------------------
  {
    files: ["**/e2e/**/*.{ts,tsx,js,jsx}"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
      "react-hooks/exhaustive-deps": "off",
    },
  },

  // -------------------------------------------------------------------
  // Scripts: relax `no-console` and `any`.
  // -------------------------------------------------------------------
  {
    files: ["scripts/**/*.{js,mjs,ts}", "apps/*/scripts/**/*.{js,mjs,ts}"],
    rules: {
      "no-console": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },

];
