/**
 * Root ESLint flat config (ESLint v9+).
 *
 * Scope: Medium (per `docs/LINTING.md`). See that doc for the value/cost
 * matrix, the HIGH-scope upgrade plan, and the rationale for every rule
 * here.
 *
 * Headline guardrails:
 *
 *  - `react-hooks/rules-of-hooks`: error. Catches the hook-rules violations
 *    TS will never see.
 *  - `react-hooks/exhaustive-deps`: warn (HIGH-scope upgrades to error).
 *  - `jsx-a11y/recommended`: catches a11y regressions at the source, ahead
 *    of the axe-core checks in the Playwright smoke suite.
 *  - `no-restricted-imports` scoped to `packages/ui/src/{ai,charts}/**`:
 *    forbids raw tamagui `Button`/`Input`/`Checkbox` imports in cross-
 *    platform components (they leak React Native a11y props to the DOM on
 *    web). Components must use the platform-forking wrappers in
 *    `packages/ui/src/primitives/*`.
 *
 * Environment globals are declared per-file-glob using the `globals`
 * package — flat config does not auto-detect environments.
 */
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import jsxA11y from "eslint-plugin-jsx-a11y";
import globals from "globals";

export default [
  // -------------------------------------------------------------------
  // Ignored paths — never lint these.
  // -------------------------------------------------------------------
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/build/**",
      "**/coverage/**",
      "**/.expo/**",
      "**/.expo-shared/**",
      "**/web-build/**",
      "**/ios/**",
      "**/android/**",
      "**/playwright-report/**",
      "**/test-results/**",
      "**/expo-env.d.ts",
      // Generated by Next.js on `next dev` — never hand-edited
      "**/next-env.d.ts",
      // Generated by Tamagui's compiler — never hand-edited, very large
      "**/.tamagui/**",
      // Generated by Prisma — never hand-edited
      "services/api/prisma/migrations/**",
      // Generated by tsup, regenerated by ./scripts/build-packages-in-docker.sh
      "packages/*/dist/**",
      // Vendored / third-party text
      "LICENSE",
    ],
  },

  // -------------------------------------------------------------------
  // Base JS + TS recommended.
  // -------------------------------------------------------------------
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // -------------------------------------------------------------------
  // Project-wide language options: ES2022 + browser + Node globals.
  // (Broad on purpose for the Medium scope. HIGH-scope narrows this
  // per-package — e.g. `services/api/**` only needs Node globals.)
  // -------------------------------------------------------------------
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2022,
        // React Native + Tamagui runtime hints used at runtime
        __DEV__: "readonly",
      },
    },
  },

  // -------------------------------------------------------------------
  // Type-aware parser for TS files (HIGH-full Phase 2 onward).
  //
  // Enables the 7 promise-related rules below to read TypeScript types.
  // Scoped to `.ts/.tsx` only so non-TS files (.cjs, .mjs, .js configs)
  // stay on the cheap parser. Adds ~30s to a full-repo lint; the savings
  // it unlocks (real promise-correctness bug catches) are worth the cost.
  //
  // `allowDefaultProject` is the escape hatch for TS files outside any
  // tsconfig include (vitest configs, ad-hoc scripts).
  // -------------------------------------------------------------------
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            "services/api/vitest.config.ts",
            "apps/web/vitest.config.ts",
            "apps/native/vitest.config.ts",
            "packages/beerjson/vitest.config.ts",
            "packages/contracts/vitest.config.ts",
            "packages/core/vitest.config.ts",
            "packages/core/src/index.d.ts",
            "packages/recipes-ui/tsup.config.ts",
            "packages/ui/tsup.config.ts",
            "services/api/prisma/seed.ts",
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // -------------------------------------------------------------------
  // Project-wide rule tweaks. MUST come before any file-glob override
  // blocks below — flat-config later blocks override earlier ones, so
  // anything we want a per-glob override (e.g. "@typescript-eslint/
  // no-explicit-any: off" for tests) to actually take effect must
  // appear AFTER this block, not before.
  // -------------------------------------------------------------------
  {
    rules: {
      // TS already enforces this and the TS error message is clearer.
      "no-unused-vars": "off",
      // Allow underscore-prefixed unused (e.g. _unusedProps).
      // Promoted from warn → error in HIGH-staged Phase 6c (2026-05-16).
      // Repo was swept warning-free across apps/native, apps/web,
      // services/api, and packages/** before this promotion landed.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // Promoted from warn → error in HIGH-staged Phase 6c (2026-05-16).
      // The repo is now `any`-free (the staged HIGH cleanup landed in
      // Phases 1–6b). When a genuine "this is dynamic" escape hatch is
      // needed, prefer typing as `unknown` and narrowing; if `any` is
      // truly unavoidable, disable per-line with a `// eslint-disable-
      // next-line @typescript-eslint/no-explicit-any -- <reason>`.
      "@typescript-eslint/no-explicit-any": "error",
      // Allow `interface X extends Y {}` (Tamagui's module augmentation
      // pattern, `interface TamaguiCustomConfig extends AppConfig {}`, and
      // similar "named type alias via interface" patterns). Still flag
      // truly empty `interface X {}` and `type X = {}` because those
      // accept any non-null value.
      "@typescript-eslint/no-empty-object-type": [
        "warn",
        { allowInterfaces: "with-single-extends" },
      ],
    },
  },

  // -------------------------------------------------------------------
  // HIGH-full Phase 2 — Tier A: Promise correctness (TS-only).
  //
  // All seven type-aware rules at `warn`. Required to be at zero
  // before the phase closes; Phase 5 promotes them to `error`.
  //
  // Scoped to `.ts/.tsx` because the rules require the type-aware
  // parser block above (which is also `.ts/.tsx`-scoped).
  //
  //  - no-floating-promises: orphan Promises that swallow rejections.
  //  - no-misused-promises: async fn passed where void return expected
  //    (event handlers, setTimeout callbacks, etc.).
  //  - await-thenable: `await` on a non-Promise (no-op signaling bug).
  //  - require-await: async fn with no `await` (return type mismatch).
  //  - prefer-promise-reject-errors / only-throw-error: reject/throw
  //    must be Error instances, not strings.
  //  - no-implied-eval: setTimeout("string"), new Function(string).
  // -------------------------------------------------------------------
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/no-misused-promises": "warn",
      "@typescript-eslint/await-thenable": "warn",
      "@typescript-eslint/require-await": "warn",
      "@typescript-eslint/prefer-promise-reject-errors": "warn",
      "@typescript-eslint/no-implied-eval": "warn",
      "@typescript-eslint/only-throw-error": "warn",
    },
  },

  // -------------------------------------------------------------------
  // React hook rules (manual; the plugin doesn't ship a flat preset).
  // -------------------------------------------------------------------
  {
    files: ["**/*.{ts,tsx,js,jsx,mjs,cjs}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      // Promoted from warn → error in HIGH-light. Catches stale-closure
      // bugs that TS cannot see (e.g. an effect that reads `state` but
      // omits it from its deps array). When a missing dep is intentional,
      // use `// eslint-disable-next-line react-hooks/exhaustive-deps --
      // <reason>`.
      "react-hooks/exhaustive-deps": "error",
    },
  },

  // -------------------------------------------------------------------
  // JSX accessibility (recommended) — only on TSX/JSX.
  // -------------------------------------------------------------------
  {
    files: ["**/*.{tsx,jsx}"],
    plugins: { "jsx-a11y": jsxA11y },
    rules: jsxA11y.configs.recommended.rules,
  },

  // -------------------------------------------------------------------
  // Cross-platform component discipline.
  //
  // Files under `packages/ui/src/{ai,charts}/**` are consumed by BOTH web
  // AND native. Importing `Button` / `Input` / `Checkbox` from raw
  // `tamagui` works on native but leaks React Native accessibility props
  // (`accessibilityLabel`, `accessibilityRole`) to the DOM on web, which
  // React 19 warns about. The project ships platform-forking primitives
  // in `packages/ui/src/primitives/{Button,Input,BrewCheckbox}.tsx` that
  // do the right thing on each platform.
  //
  // This rule forbids the raw imports in the cross-platform folders only;
  // web-only pages (`apps/web/**`) and native-only screens
  // (`apps/native/**`) are unaffected.
  // -------------------------------------------------------------------
  {
    files: ["packages/ui/src/ai/**/*.{ts,tsx}", "packages/ui/src/charts/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "tamagui",
              importNames: ["Button", "Input", "Checkbox"],
              message:
                "Cross-platform components must use platform-forking primitives: import { Button } from '../primitives/Button', { Input } from '../primitives/Input', { BrewCheckbox } from '../primitives/BrewCheckbox'. Raw tamagui Button/Input/Checkbox leak accessibilityLabel to the DOM on web. See docs/LINTING.md.",
            },
          ],
        },
      ],
    },
  },

  // -------------------------------------------------------------------
  // CommonJS files: allow `require()` and CJS globals.
  // (`.cjs` files are intentionally CommonJS; `.js` files in legacy
  // configs like babel.config.js, metro.config.js can use either.)
  // -------------------------------------------------------------------
  {
    files: ["**/*.cjs", "**/babel.config.js", "**/metro.config.js"],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        ...globals.node,
        ...globals.commonjs,
      },
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },

  // -------------------------------------------------------------------
  // Test files: relax a few rules.
  // -------------------------------------------------------------------
  {
    files: [
      "**/*.{test,spec}.{ts,tsx,js,jsx}",
      "**/tests/**",
      "**/e2e/**",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-expressions": "off",
    },
  },

  // -------------------------------------------------------------------
  // Playwright e2e fixtures: Playwright's `use` fixture parameter has the
  // same name as React 19's `use()` hook. ESLint's `react-hooks` plugin
  // can't tell them apart, so it false-positives on every Playwright
  // fixture function. Disable the hook rules in e2e directories — these
  // files are not React.
  // -------------------------------------------------------------------
  {
    files: ["**/e2e/**/*.{ts,tsx,js,jsx}"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
      "react-hooks/exhaustive-deps": "off",
    },
  },

  // -------------------------------------------------------------------
  // Scripts: relax `no-console` and `any`.
  // -------------------------------------------------------------------
  {
    files: ["scripts/**/*.{js,mjs,ts}", "apps/*/scripts/**/*.{js,mjs,ts}"],
    rules: {
      "no-console": "off",
      "@typescript-eslint/no-explicit-any": "off",
    },
  },

];
