-- AlterTable
ALTER TABLE "RecipeWaterSettings" ADD COLUMN     "boilAcidType" TEXT NOT NULL DEFAULT 'phosphoric',
ADD COLUMN     "boilAcidificationMode" TEXT NOT NULL DEFAULT 'targetPh',
ADD COLUMN     "boilDilutionWaterProfileId" TEXT,
ADD COLUMN     "boilDilutionWaterVolumeLiters" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "boilLastAcidRequiredGrams" DOUBLE PRECISION,
ADD COLUMN     "boilLastAcidRequiredKg" DOUBLE PRECISION,
ADD COLUMN     "boilLastAcidRequiredMl" DOUBLE PRECISION,
ADD COLUMN     "boilLastAcidRequiredTsp" DOUBLE PRECISION,
ADD COLUMN     "boilLastCalculatedAt" TIMESTAMP(3),
ADD COLUMN     "boilLastChlorideAddedPpm" DOUBLE PRECISION,
ADD COLUMN     "boilLastFinalAlkalinityPpmCaCO3" DOUBLE PRECISION,
ADD COLUMN     "boilLastSulfateAddedPpm" DOUBLE PRECISION,
ADD COLUMN     "boilManualAcidAddedGrams" DOUBLE PRECISION,
ADD COLUMN     "boilManualAcidAddedMl" DOUBLE PRECISION,
ADD COLUMN     "boilManualLastAchievedPh" DOUBLE PRECISION,
ADD COLUMN     "boilManualLastCalculatedAt" TIMESTAMP(3),
ADD COLUMN     "boilManualLastChlorideAddedPpm" DOUBLE PRECISION,
ADD COLUMN     "boilManualLastFinalAlkalinityPpmCaCO3" DOUBLE PRECISION,
ADD COLUMN     "boilManualLastSulfateAddedPpm" DOUBLE PRECISION,
ADD COLUMN     "boilOverallLastCalculatedAt" TIMESTAMP(3),
ADD COLUMN     "boilOverallLastResultJson" JSONB,
ADD COLUMN     "boilSaltAdditionsJson" JSONB,
ADD COLUMN     "boilSaltsLastResultJson" JSONB,
ADD COLUMN     "boilSourceWaterProfileId" TEXT,
ADD COLUMN     "boilStartingAlkalinityPpmCaCO3" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "boilStartingPh" DOUBLE PRECISION NOT NULL DEFAULT 7.0,
ADD COLUMN     "boilStrengthKind" TEXT NOT NULL DEFAULT 'percent',
ADD COLUMN     "boilStrengthValue" DOUBLE PRECISION,
ADD COLUMN     "boilTapWaterVolumeLiters" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "boilTargetPh" DOUBLE PRECISION NOT NULL DEFAULT 5.6,
ADD COLUMN     "boilTargetWaterProfileId" TEXT,
ADD COLUMN     "boilWaterVolumeLiters" DOUBLE PRECISION NOT NULL DEFAULT 0;
