/**
 * Brewery path → contracts parser map (OpenAPI path key → runtime parse).
 * Compile-time path types live on each facade module via BreweryOpenApiPaths.
 */
export const BREWERY_FACADE_PARSER_MAP = {
  "/recipes/{id}/export/beerjson": "BeerJsonExportResponseSchema",
  "/recipes/export/beerjson": "BeerJsonExportResponseSchema",
  "/admin/ingredients/sync-runs": "IngredientSyncRunsResponseSchema",
  "/admin/ingredients/sync": "IngredientSyncResponseSchema",
  "/recipes": "parseRecipesListResponse / RecipeResponseSchema (POST)",
  "/recipes/{id}": "RecipeResponseSchema / OkResponseSchema (DELETE)",
  "/recipes/{id}/versions": "RecipeVersionsResponseSchema / RecipeResponseSchema (POST)",
  "/recipes/{id}/duplicate": "RecipeResponseSchema",
  "/recipes/import/preview": "RecipeImportPreviewResponseSchema",
  "/recipes/import": "RecipeImportResponseSchema",
  "/recipes/import/bulk/preview": "RecipeBulkImportPreviewResponseSchema",
  "/recipes/import/bulk": "RecipeBulkImportResponseSchema",
  "/styles": "StylesListResponseSchema",
  "/ingredients/fermentables": "FermentablesListResponseSchema",
  "/ingredients/hops": "HopsListResponseSchema",
  "/ingredients/yeasts": "YeastsListResponseSchema",
  "/brew-sessions/{brewSessionId}": "BrewSessionDetailResponseSchema",
  "/brew-sessions/{brewSessionId}/steps": "BrewSessionStepsResponseSchema",
  "/brew-sessions/{brewSessionId}/integrations/attachments": "IntegrationAttachmentsResponseSchema",
  "/brew-sessions/{brewSessionId}/integrations/readings": "IntegrationReadingsResponseSchema",
  "/inventory": "InventoryListResponseSchema / InventoryItemResponseSchema",
  "/inventory/{id}": "InventoryItemResponseSchema / OkResponseSchema (DELETE)",
  "/equipment-profiles": "EquipmentProfilesListResponseSchema / EquipmentProfileResponseSchema",
  "/equipment-profiles/{id}": "EquipmentProfileResponseSchema / OkResponseSchema (DELETE)",
  "/brewday-settings": "BrewdaySettingsResponseSchema",
  "/recipes/{recipeId}/brew-sessions": "parseBrewSessionsListResponse",
  "/recipes/{id}/water-hub-summary": "parseRecipeWaterHubSummaryResponse",
  "/water-profiles": "parseWaterProfilesResponse / WaterProfileResponseSchema",
  "/water-profiles/{id}/verify": "OkResponseSchema",
  "/water-profiles/{id}/unverify": "OkResponseSchema",
  "/water-profiles/{id}": "OkResponseSchema (DELETE)",
  "/recipes/{id}/water-settings": "RecipeWaterSettingsGetResponseSchema / RecipeWaterSettingsPutResponseSchema",
  "/recipes/{id}/water-settings/mash/compute-and-save": "parseMashComputeAndSaveResponse",
  "/recipes/{id}/water-settings/sparge/compute-and-save": "parseSpargeComputeAndSaveResponse",
  "/recipes/{id}/water-settings/boil/compute-and-save": "parseBoilComputeAndSaveResponse",
  "/water-calc/salt-additions": "WaterCalcWithDerivationResponseSchema",
  "/water-calc/mash-ph-estimate": "WaterCalcResultOnlyResponseSchema",
  "/water-calc/mash-overall": "WaterCalcWithDerivationResponseSchema",
  "/water-calc/sparge-overall": "WaterCalcWithDerivationResponseSchema",
  "/water-calc/boil-overall": "WaterCalcWithDerivationResponseSchema",
  "/water-calc/sparge-acidification": "WaterCalcWithDerivationResponseSchema",
  "/water-calc/sparge-acidification-manual": "WaterCalcWithDerivationResponseSchema",
  "/water-calc/mash-acidification": "WaterCalcWithDerivationResponseSchema",
  "/water-calc/mash-acidification-manual": "WaterCalcWithDerivationResponseSchema",
  "/water-calc/mash-acidification-target-mash-ph": "WaterCalcResultOnlyResponseSchema",
} as const;
