// This file is generated by scripts/generate-manifest.mjs
// Do not edit manually.

export const mediaManifest = {
  "yeast/dilution-1-100.png": { publicPath: "/media/yeast/dilution-1-100.d697cdbaee75.png", sha256: "d697cdbaee752b09137c0c5a51810b0fc6aec869124281d31b46d2c7fbf6595a", bytes: 6522 },
  "yeast/hemocytometer-5-squares.png": { publicPath: "/media/yeast/hemocytometer-5-squares.fe085a0d2bf9.png", sha256: "fe085a0d2bf9d595d1b4c95aa277f549b4e58b1fedfc1711d36901b9eba2993c", bytes: 10417 },
} as const;

export type MediaAssetKey = keyof typeof mediaManifest;
